--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IvanCraft623/FormAPI
branches:
- stable
projects:
  FormAPI:
    path: ""
  libFormAPI:
    path: ""
    type: library
    model: virion
...
